'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Ingles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LoxusMedicineUsers.Ingles", GetType(Ingles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Admin.
        '''</summary>
        Friend Shared ReadOnly Property BTN_LogAdmin() As String
            Get
                Return ResourceManager.GetString("BTN_LogAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login.
        '''</summary>
        Friend Shared ReadOnly Property BTN_Login() As String
            Get
                Return ResourceManager.GetString("BTN_Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medic.
        '''</summary>
        Friend Shared ReadOnly Property BTN_LogMedic() As String
            Get
                Return ResourceManager.GetString("BTN_LogMedic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User.
        '''</summary>
        Friend Shared ReadOnly Property BTN_LogUser() As String
            Get
                Return ResourceManager.GetString("BTN_LogUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sign Up.
        '''</summary>
        Friend Shared ReadOnly Property BTN_Registrarse() As String
            Get
                Return ResourceManager.GetString("BTN_Registrarse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Code Invalid.
        '''</summary>
        Friend Shared ReadOnly Property LBL_CodAdmin() As String
            Get
                Return ResourceManager.GetString("LBL_CodAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medic Code.
        '''</summary>
        Friend Shared ReadOnly Property LBL_CodMedic() As String
            Get
                Return ResourceManager.GetString("LBL_CodMedic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property LBL_Contraseña() As String
            Get
                Return ResourceManager.GetString("LBL_Contraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create Account, click here.
        '''</summary>
        Friend Shared ReadOnly Property LBL_CrearCuenta() As String
            Get
                Return ResourceManager.GetString("LBL_CrearCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password Invalid.
        '''</summary>
        Friend Shared ReadOnly Property LBL_ErrorContraseña() As String
            Get
                Return ResourceManager.GetString("LBL_ErrorContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Code Invalid.
        '''</summary>
        Friend Shared ReadOnly Property LBL_ErrorMedico() As String
            Get
                Return ResourceManager.GetString("LBL_ErrorMedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username Invalid.
        '''</summary>
        Friend Shared ReadOnly Property LBL_ErrorUsuario() As String
            Get
                Return ResourceManager.GetString("LBL_ErrorUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You donot have an account? create in minutes, click here.
        '''</summary>
        Friend Shared ReadOnly Property LBL_Infocuenta() As String
            Get
                Return ResourceManager.GetString("LBL_Infocuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Maximum characters 20.
        '''</summary>
        Friend Shared ReadOnly Property LBL_MaxPass() As String
            Get
                Return ResourceManager.GetString("LBL_MaxPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Maximum characters 20.
        '''</summary>
        Friend Shared ReadOnly Property LBL_MaxUser() As String
            Get
                Return ResourceManager.GetString("LBL_MaxUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recover Password.
        '''</summary>
        Friend Shared ReadOnly Property LBL_Recuperar() As String
            Get
                Return ResourceManager.GetString("LBL_Recuperar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Firstname.
        '''</summary>
        Friend Shared ReadOnly Property LBL_RegApe() As String
            Get
                Return ResourceManager.GetString("LBL_RegApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property LBL_RegContra() As String
            Get
                Return ResourceManager.GetString("LBL_RegContra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property LBL_RegEmail() As String
            Get
                Return ResourceManager.GetString("LBL_RegEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property LBL_RegNom() As String
            Get
                Return ResourceManager.GetString("LBL_RegNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username .
        '''</summary>
        Friend Shared ReadOnly Property LBL_RegUsu() As String
            Get
                Return ResourceManager.GetString("LBL_RegUsu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User.
        '''</summary>
        Friend Shared ReadOnly Property LBL_Usuario() As String
            Get
                Return ResourceManager.GetString("LBL_Usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log In.
        '''</summary>
        Friend Shared ReadOnly Property Titulo_Login() As String
            Get
                Return ResourceManager.GetString("Titulo_Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sign In.
        '''</summary>
        Friend Shared ReadOnly Property Titulo_Registro() As String
            Get
                Return ResourceManager.GetString("Titulo_Registro", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
